name:                griff
version:             0.1.0.0
github:              "takoeight0821/griff"
license:             BSD3
author:              "Yuya Kono"
maintainer:          "takohati0821@gmail.com"
copyright:           "2019 Yuya Kono"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/takoeight0821/griff#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- extra
- fixed-vector
- fused-effects
- generic-lens
- lens
- llvm-hs-pure
- megaparsec
- mtl
- outputable
- parser-combinators
- prettyprinter
- text

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-record-updates

library:
  source-dirs: src

executables:
  griff-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - griff

tests:
  griff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - griff
    - hspec
    - hspec-discover
