library:
  source-dirs: src
tests:
  griff-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - griff
copyright: 2020 Yuya Kono
maintainer: takohati0821@gmail.com
dependencies:
- llvm-hs-pure
- base >= 4.7 && < 5
- containers
- lens
- mtl
- bytestring
- megaparsec
- parser-combinators
- pretty
- pretty-simple
- text
- transformers
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-name-shadowing
  - -j4
  - +RTS -A128m -n2m -qg -RTS
  - -fwrite-ide-info
  - -hiedir=.hie
name: griff
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Yuya Kono
github: takoeight0821/griff
license: BSD3
executables:
  griff-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - griff
description: Please see the README on GitHub at <https://github.com/takoeight0821/griff#readme>
